version: "3.5"

services:
    trexproxy:
        image: darwin1968/trexproxy-image:latest
        container_name: trexproxy
        ports:
            - 8081:443
        networks:
            - trexnet

    trexwebapp:
        image: darwin1968/trexapp-image:latest
        container_name: trexwebapp
        ports:
            - 8082:443
        networks:
            - trexnet    

    trexwebapi:
        image: darwin1968/trexwebapi:latest
        container_name: trexwebapi
        ports:
            - 8083:80
            - 8084:443
        networks:
            - trexnet    


networks: 
    trexnet:
